### ISSUE TITLE
Feature Request: Support adding scenes to the custom folder

### ISSUE THREAD

**Issue by caewok** [SvenWerlen/moulinette-scenes#3]
I see that Moulinette creates a scenes/custom folder but I could not find any information on what I would have to add to it to have it import custom scenes. This [Discord conversation](https://discord.com/channels/811798496499728414/850477869289177108/876614397840216064) suggests that Moulinette does not (yet) support that, so I thought I would put in an official request for that use case.

This would be particularly useful to allow me (and others) to offload a lot of large scenes to S3. I am aware that Moulinette will import images as a scene, but that of course is not the same as importing a scene with walls and other data. Thanks!

**Comment by SvenWerlen** [comment]
- Moulinette (the module) won't support this because scenes have dependencies (tiles, sounds, notes, etc.) that cannot be easily be handled by the module itself
- Moulinette Cloud support it for creators but not yet for users (private storage). I'm planning to work on this in September/October.
- Other modules like Scene Packer could help, too. I'm planning to support it on Moulinette Cloud.
